In [23]:
print("hello")
a = 1

hello


In [24]:
print(a)

1


In [25]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
a +=1

In [27]:
print("hello")

hello


# welcome
## he
**A**
~~s~~

In [31]:
%timeit [i**2 for i in range(1000)]

531 µs ± 61.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
%%timeit
L = []
for i in range(1000):
    L.append(i**2)

625 µs ± 55.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [1]:
import numpy as np
np.__version__

'1.15.4'

In [40]:
x = np.array([i for i in range(10)])

In [42]:
x.dtype

dtype('int32')

In [45]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [47]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.full((10,5),666).T.dot(np.arange(0,20,2))

array([59940, 59940, 59940, 59940, 59940])

In [57]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [71]:
np.random.randint(0,10,(3,5)).dot(np.random.randint(0,10,(5,3)))

array([[ 66,  95,  63],
       [ 73,  74,  56],
       [ 80, 101,  35]])

In [76]:
np.random.random((5,3))

array([[0.48678052, 0.1536739 , 0.82846513],
       [0.19136857, 0.27040895, 0.56103442],
       [0.90238039, 0.85178834, 0.41808196],
       [0.39347627, 0.01622051, 0.29921337],
       [0.35377822, 0.89350267, 0.78613657]])

In [81]:
np.random.normal(0,1,(5,3))

array([[-3.09487059,  3.39351678, -0.12666878],
       [-0.93713026,  0.56552529,  0.3158975 ],
       [-0.79572225,  0.50507572,  0.32482413],
       [ 0.9608153 ,  0.03026866,  0.57605275],
       [-0.06992037,  0.64549479, -0.6055902 ]])

In [83]:
np.arange(0,30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [86]:
X = np.arange(0,30).reshape(5,6)
print(X.size)
print(X.shape)
X.ndim

30
(5, 6)


2

In [144]:
%timeit X[np.random.randint(0,X.shape[0]),np.random.randint(0,X.shape[1])]


5.83 µs ± 426 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [145]:
%timeit X[np.random.randint(0,X.shape[0])][np.random.randint(0,X.shape[1])]

5.95 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [141]:
X.shape

(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [6]:
np.concatenate([x,y]).reshape(2,3)

array([[1, 2, 3],
       [3, 2, 1]])

In [11]:
np.concatenate([np.array([[5,6],[7,8,9]]),np.array([[1,2],[3,4]])])

ValueError: all the input arrays must have same number of dimensions

In [16]:
m = np.arange(10).reshape(2,5)
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
pinvm = np.linalg.pinv(m)

In [18]:
m.dot(pinvm)

array([[ 1.00000000e+00, -1.66533454e-16],
       [ 1.33226763e-15,  1.00000000e+00]])

In [19]:
pinvm.dot(m)

array([[ 6.00000000e-01,  4.00000000e-01,  2.00000000e-01,
        -7.77156117e-16, -2.00000000e-01],
       [ 4.00000000e-01,  3.00000000e-01,  2.00000000e-01,
         1.00000000e-01, -6.66133815e-16],
       [ 2.00000000e-01,  2.00000000e-01,  2.00000000e-01,
         2.00000000e-01,  2.00000000e-01],
       [-6.93889390e-17,  1.00000000e-01,  2.00000000e-01,
         3.00000000e-01,  4.00000000e-01],
       [-2.00000000e-01,  5.55111512e-17,  2.00000000e-01,
         4.00000000e-01,  6.00000000e-01]])

In [20]:
L = np.random.random(10000)

In [21]:
%timeit sum(L)

2.17 ms ± 313 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%timeit np.sum(L)

9.63 µs ± 937 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
np.max(L)

0.9998113501306917

In [25]:
np.array([1,2]) == np.array([3,2])

array([False,  True])

In [29]:
~np.array([True,False])

array([False,  True])

In [31]:
for i in np.array([[1,2],[3,4]]):
    print(i)

[1 2]
[3 4]


In [7]:
np.linalg.eig(np.array([[4,-2],[1,1]]))

(array([3., 2.]), array([[0.89442719, 0.70710678],
        [0.4472136 , 0.70710678]]))

In [8]:
np.array([[4,-2],[1,1]]).dot(np.array([0.89442719,0.4472]))

array([2.68330876, 1.34162719])

In [10]:
B = np.array([[1,2],[3,4]])

In [11]:
P = np.array([[5,6],[7,8]])

In [12]:
iP = np.linalg.inv(P)

In [13]:
A = iP.dot(B).dot(P)

In [14]:
A

array([[ 53.,  62.],
       [-41., -48.]])

In [15]:
np.linalg.eig(A)

(array([ 5.37228132, -0.37228132]), array([[ 0.79302307, -0.75786917],
        [-0.60919161,  0.65240656]]))

In [16]:
np.linalg.eig(B)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [17]:
x1, x2 = np.linalg.eig(A)

In [21]:
x3 = np.identity(2)
x3

array([[1., 0.],
       [0., 1.]])

In [25]:
D = x1*x3

In [26]:
x2.dot(D).dot(np.linalg.inv(x2))

array([[ 53.,  62.],
       [-41., -48.]])

In [33]:
def diag(A: np.ndarray):
    lambdas, P = np.linalg.eig(A)
    assert np.linalg.matrix_rank(P) == P.shape[0]
    return np.identity(A.shape[0]) * lambdas, P

In [34]:
diag(B)

(array([[-0.37228132,  0.        ],
        [-0.        ,  5.37228132]]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [35]:
diag(A)

(array([[ 5.37228132, -0.        ],
        [ 0.        , -0.37228132]]), array([[ 0.79302307, -0.75786917],
        [-0.60919161,  0.65240656]]))

In [36]:
diag(np.array([[3,1],[0,3]]))

AssertionError: 

In [37]:
z = np.array([[3,1],[0,3]])

In [40]:
z.dot(z).dot(z).dot(z)

array([[ 81, 108],
       [  0,  81]])

In [42]:
A.dot(A)

array([[ 267.,  310.],
       [-205., -238.]])

In [43]:
diag(A)[1].dot(diag(A)[0].dot(diag(A)[0])).dot(np.linalg.inv(diag(A)[1]))

array([[ 267.,  310.],
       [-205., -238.]])

In [3]:
np.linalg.eig(np.array([[1,2,3],[2,3,4],[3,4,4]]))

(array([ 9.10977223, -1.        , -0.10977223]),
 array([[-0.40408749, -0.66666667,  0.6263137 ],
        [-0.58994144, -0.33333333, -0.73543047],
        [-0.69905822,  0.66666667,  0.25859846]]))

In [4]:
np.array([[1,2,3],[2,3,4],[3,4,4]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 4]])