In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4])

In [3]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [6]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
s2 = pd.Series(np.arange(10))

In [8]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [9]:
s3  =pd.Series({"sda":12,"sadd":2})

In [10]:
s3

sda     12
sadd     2
dtype: int64

In [11]:
s3.index

Index(['sda', 'sadd'], dtype='object')

In [12]:
s3.values

array([12,  2], dtype=int64)

In [24]:
s4 = pd.Series([1,3,4],index = [7654,423,542])

In [15]:
s4

7654    1
423     3
542     4
dtype: int64

In [18]:
s4[423]

3

In [19]:
s4[s4>2]

423    3
542    4
dtype: int64

In [20]:
s4>2

7654    False
423      True
542      True
dtype: bool

In [34]:
s4.to_dict()

{7654: 1, 423: 3, 542: 4}

In [35]:
s4 = pd.Series([1,2,3,4], index = ['A','B','C','D'])

In [59]:
s5 = pd.Series(s4,index = ['A','A','C','D',"E"])

In [47]:
s5

A    1.0
A    1.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [48]:
pd.isnull(s5)

A    False
A    False
C    False
D    False
E     True
dtype: bool

In [50]:
pd.notnull(s5)

A     True
A     True
C     True
D     True
E    False
dtype: bool

In [51]:
s5.name = "SD"

In [52]:
s5

A    1.0
A    1.0
C    3.0
D    4.0
E    NaN
Name: SD, dtype: float64

In [55]:
s5.index = ['A','B','C','D',"F"]

In [60]:
s5

A    1.0
A    1.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [61]:
s5['A'] = 2
s5

A    2.0
A    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [62]:
from pandas import Series, DataFrame

In [64]:
import webbrowser
link = "https://www.tiobe.com/tiobe-index/"
webbrowser.open(link)

True

In [65]:
data = pd.read_clipboard()

In [66]:
data

Feb 2019  Feb 2018  Change  Programming Language  Ratings Change.1
0          1         1     NaN                  Java  15.876%   +0.89%
1          2         2     NaN                     C  12.424%   +0.57%
2          3         4  change                Python   7.574%   +2.41%
3          4         3  change                   C++   7.444%   +1.72%
4          5         6  change     Visual Basic .NET   7.095%   +3.02%
5          6         8  change            JavaScript   2.848%   -0.32%
6          7         5  change                    C#   2.846%   -1.61%
7          8         7  change                   PHP   2.271%   -1.15%
8          9        11  change                   SQL   1.900%   -0.46%
9         10        20  change           Objective-C   1.447%   +0.32%
10        11        15  change     Assembly language   1.377%   -0.46%
11        12        19  change                MATLAB   1.196%   -0.03%
12        13        17  change                  Perl   1.102%   -0.66%
13        14         9  change  Delphi/Object Pascal   1.066%   -1.52%
14        15        13  change                     R   1.043%   -1.04%
15        16        10  change                  Ruby   1.037%   -1.50%
16        17        12  change          Visual Basic   0.991%   -1.19%
17        18        18     NaN                    Go   0.960%   -0.46%
18        19        49  change                Groovy   0.936%   +0.75%
19        20        16  change                 Swift   0.918%   -0.88%

In [68]:
data["Change"]

0        NaN
1        NaN
2     change
3     change
4     change
5     change
6     change
7     change
8     change
9     change
10    change
11    change
12    change
13    change
14    change
15    change
16    change
17       NaN
18    change
19    change
Name: Change, dtype: object

In [71]:
data.Ratings

0     15.876%
1     12.424%
2      7.574%
3      7.444%
4      7.095%
5      2.848%
6      2.846%
7      2.271%
8      1.900%
9      1.447%
10     1.377%
11     1.196%
12     1.102%
13     1.066%
14     1.043%
15     1.037%
16     0.991%
17     0.960%
18     0.936%
19     0.918%
Name: Ratings, dtype: object

In [72]:
data.columns

Index(['Feb 2019', 'Feb 2018', 'Change', 'Programming Language', 'Ratings',
       'Change.1'],
      dtype='object')

In [73]:
data_new = DataFrame(data, columns=["Programming Language","Feb 2019","Feb 2018", "Ratings"])

In [74]:
data_new

Programming Language  Feb 2019  Feb 2018  Ratings
0                   Java         1         1  15.876%
1                      C         2         2  12.424%
2                 Python         3         4   7.574%
3                    C++         4         3   7.444%
4      Visual Basic .NET         5         6   7.095%
5             JavaScript         6         8   2.848%
6                     C#         7         5   2.846%
7                    PHP         8         7   2.271%
8                    SQL         9        11   1.900%
9            Objective-C        10        20   1.447%
10     Assembly language        11        15   1.377%
11                MATLAB        12        19   1.196%
12                  Perl        13        17   1.102%
13  Delphi/Object Pascal        14         9   1.066%
14                     R        15        13   1.043%
15                  Ruby        16        10   1.037%
16          Visual Basic        17        12   0.991%
17                    Go        18        18   0.960%
18                Groovy        19        49   0.936%
19                 Swift        20        16   0.918%

In [85]:
df_new = DataFrame(data, columns=["Programming Language","Feb 2019","Feb 2018", "Feb 2020", "Ratings"])
df_new

Programming Language  Feb 2019  Feb 2018  Feb 2020  Ratings
0                   Java         1         1       NaN  15.876%
1                      C         2         2       NaN  12.424%
2                 Python         3         4       NaN   7.574%
3                    C++         4         3       NaN   7.444%
4      Visual Basic .NET         5         6       NaN   7.095%
5             JavaScript         6         8       NaN   2.848%
6                     C#         7         5       NaN   2.846%
7                    PHP         8         7       NaN   2.271%
8                    SQL         9        11       NaN   1.900%
9            Objective-C        10        20       NaN   1.447%
10     Assembly language        11        15       NaN   1.377%
11                MATLAB        12        19       NaN   1.196%
12                  Perl        13        17       NaN   1.102%
13  Delphi/Object Pascal        14         9       NaN   1.066%
14                     R        15        13       NaN   1.043%
15                  Ruby        16        10       NaN   1.037%
16          Visual Basic        17        12       NaN   0.991%
17                    Go        18        18       NaN   0.960%
18                Groovy        19        49       NaN   0.936%
19                 Swift        20        16       NaN   0.918%

In [86]:
df_new["Feb 2020"] = np.arange(20)

In [96]:
df_new

Programming Language  Feb 2019  Feb 2018  Feb 2020  Ratings
0                   Java         1         1         0  15.876%
1                      C         2         2         1  12.424%
2                 Python         3         4         2   7.574%
3                    C++         4         3         3   7.444%
4      Visual Basic .NET         5         6       200   7.095%
5             JavaScript         6         8         5   2.848%
6                     C#         7         5       100   2.846%
7                    PHP         8         7         7   2.271%
8                    SQL         9        11         8   1.900%
9            Objective-C        10        20         9   1.447%
10     Assembly language        11        15        10   1.377%
11                MATLAB        12        19        11   1.196%
12                  Perl        13        17        12   1.102%
13  Delphi/Object Pascal        14         9        13   1.066%
14                     R        15        13        14   1.043%
15                  Ruby        16        10        15   1.037%
16          Visual Basic        17        12        16   0.991%
17                    Go        18        18        17   0.960%
18                Groovy        19        49        18   0.936%
19                 Swift        20        16        19   0.918%

In [93]:
a = df_new["Feb 2020"]

In [95]:
a[4] = 200

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [97]:
data.values

array([[1, 1, nan, 'Java', '15.876%', '+0.89%'],
       [2, 2, nan, 'C', '12.424%', '+0.57%'],
       [3, 4, 'change', 'Python', '7.574%', '+2.41%'],
       [4, 3, 'change', 'C++', '7.444%', '+1.72%'],
       [5, 6, 'change', 'Visual Basic .NET', '7.095%', '+3.02%'],
       [6, 8, 'change', 'JavaScript', '2.848%', '-0.32%'],
       [7, 5, 'change', 'C#', '2.846%', '-1.61%'],
       [8, 7, 'change', 'PHP', '2.271%', '-1.15%'],
       [9, 11, 'change', 'SQL', '1.900%', '-0.46%'],
       [10, 20, 'change', 'Objective-C', '1.447%', '+0.32%'],
       [11, 15, 'change', 'Assembly language', '1.377%', '-0.46%'],
       [12, 19, 'change', 'MATLAB', '1.196%', '-0.03%'],
       [13, 17, 'change', 'Perl', '1.102%', '-0.66%'],
       [14, 9, 'change', 'Delphi/Object Pascal', '1.066%', '-1.52%'],
       [15, 13, 'change', 'R', '1.043%', '-1.04%'],
       [16, 10, 'change', 'Ruby', '1.037%', '-1.50%'],
       [17, 12, 'change', 'Visual Basic', '0.991%', '-1.19%'],
       [18, 18, nan, 'Go', '0.960%'

In [107]:
a = data.iterrows()

In [127]:
a.send(5)

(4, Feb 2019                                5
 Feb 2018                                6
 Change                             change
 Programming Language    Visual Basic .NET
 Ratings                            7.095%
 Change.1                           +3.02%
 Name: 4, dtype: object)

In [134]:
pd.read_clipboard()

Feb  2019   Feb.1           2018    Change Programming Language Ratings  \
0     1     1    Java        15.876%    +0.89%        None     None    None   
1     2     2       C        12.424%    +0.57%        None     None    None   
2     3     4  change         Python    7.574%      +2.41%     None    None   
3     4     3  change            C++    7.444%      +1.72%     None    None   
4     5     6  change         Visual     Basic        .NET   7.095%  +3.02%   
5     6     8  change     JavaScript    2.848%      -0.32%     None    None   
6     7     5  change             C#    2.846%      -1.61%     None    None   
7     8     7  change            PHP    2.271%      -1.15%     None    None   
8     9    11  change            SQL    1.900%      -0.46%     None    None   
9    10    20  change    Objective-C    1.447%      +0.32%     None    None   
10   11    15  change       Assembly  language      1.377%   -0.46%    None   
11   12    19  change         MATLAB    1.196%      -0.03%     None    None   
12   13    17  change           Perl    1.102%      -0.66%     None    None   
13   14     9  change  Delphi/Object    Pascal      1.066%   -1.52%    None   
14   15    13  change              R    1.043%      -1.04%     None    None   
15   16    10  change           Ruby    1.037%      -1.50%     None    None   
16   17    12  change         Visual     Basic      0.991%   -1.19%    None   
17   18    18      Go         0.960%    -0.46%        None     None    None   
18   19    49  change         Groovy    0.936%      +0.75%     None    None   
19   20    16  change          Swift    0.918%      -0.88%     None    None   

    Change.1  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
5        NaN  
6        NaN  
7        NaN  
8        NaN  
9        NaN  
10       NaN  
11       NaN  
12       NaN  
13       NaN  
14       NaN  
15       NaN  
16       NaN  
17       NaN  
18       NaN  
19       NaN

In [135]:
s1 = Series([1,2,3,4],index = ["A","B","C","D"])

In [136]:
s1

A    1
B    2
C    3
D    4
dtype: int64

In [137]:
s1.reindex(np.arange(4))

0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

In [142]:
s1.reindex(["A","D","B","C"])

A    1
D    4
B    2
C    3
dtype: int64

In [144]:
s = DataFrame(np.random.random((5,5)),index = ["A","B","D","E","F"], columns= ["c1",'c2','c3','c5','c6'])

In [150]:
s.reindex(index = ["A","B","C","D","E","F"], fill_value=[2,3,4,5,6])

c1               c2               c3               c5  \
A         0.795676         0.686971         0.677441         0.673348   
B         0.933118         0.722547          0.63065         0.978142   
C  [2, 3, 4, 5, 6]  [2, 3, 4, 5, 6]  [2, 3, 4, 5, 6]  [2, 3, 4, 5, 6]   
D         0.266681         0.053617         0.242216         0.210198   
E         0.509397         0.165521           0.3256          0.51972   
F         0.716981         0.710634         0.763624        0.0497432   

                c6  
A        0.0713661  
B         0.853915  
C  [2, 3, 4, 5, 6]  
D          0.43178  
E         0.792667  
F         0.675041

In [146]:
s

c1        c2        c3        c5        c6
A  0.795676  0.686971  0.677441  0.673348  0.071366
B  0.933118  0.722547  0.630650  0.978142  0.853915
D  0.266681  0.053617  0.242216  0.210198  0.431780
E  0.509397  0.165521  0.325600  0.519720  0.792667
F  0.716981  0.710634  0.763624  0.049743  0.675041

In [151]:
np.nan

nan

In [159]:
print(np.nan == np.nan)
print(np.nan is np.nan)

False
True


In [164]:
a = [1,2,3]
list(map(lambda x : x**2, a))

[1, 4, 9]